{"trial_id": "1", "hyperparameters": {"space": [{"class_name": "Boolean", "config": {"name": "batchNorm1", "default": false, "conditions": []}}, {"class_name": "Boolean", "config": {"name": "batchNorm2", "default": false, "conditions": []}}, {"class_name": "Choice", "config": {"name": "up_interpolation1", "default": "area", "conditions": [], "values": ["area", "bicubic", "bilinear", "gaussian", "lanczos3", "lanczos5", "mitchellcubic", "nearest"], "ordered": false}}, {"class_name": "Boolean", "config": {"name": "batchNorm3", "default": false, "conditions": []}}, {"class_name": "Boolean", "config": {"name": "batchNorm4", "default": false, "conditions": []}}, {"class_name": "Choice", "config": {"name": "up_interpolation2", "default": "area", "conditions": [], "values": ["area", "bicubic", "bilinear", "gaussian", "lanczos3", "lanczos5", "mitchellcubic", "nearest"], "ordered": false}}, {"class_name": "Float", "config": {"name": "lr", "default": 0.0001, "conditions": [], "min_value": 0.0001, "max_value": 0.01, "step": null, "sampling": "log"}}, {"class_name": "Boolean", "config": {"name": "shuffle", "default": false, "conditions": []}}, {"class_name": "Int", "config": {"name": "batch_size", "default": null, "conditions": [], "min_value": 32, "max_value": 64, "step": 8, "sampling": "linear"}}], "values": {"batchNorm1": false, "batchNorm2": false, "up_interpolation1": "area", "batchNorm3": false, "batchNorm4": false, "up_interpolation2": "lanczos5", "lr": 0.002752738682669076, "shuffle": true, "batch_size": 32}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/dist-packages/keras_tuner/engine/base_tuner.py\", line 266, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/usr/local/lib/python3.8/dist-packages/keras_tuner/engine/base_tuner.py\", line 231, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/usr/local/lib/python3.8/dist-packages/keras_tuner/engine/tuner.py\", line 287, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/usr/local/lib/python3.8/dist-packages/keras_tuner/engine/tuner.py\", line 214, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"<ipython-input-5-8e653f4116a0>\", line 45, in fit\n    return model.fit(\n  File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py\", line 1269, in autograph_handler\n    raise e.ag_error_metadata.to_exception(e)\ntensorflow.python.autograph.impl.api.StagingError: in user code:\n\n    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1249, in train_function  *\n        return step_function(self, iterator)\n    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1233, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1222, in run_step  **\n        outputs = model.train_step(data)\n    File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1027, in train_step\n        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)\n    File \"/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 526, in minimize\n        grads_and_vars = self.compute_gradients(loss, var_list, tape)\n    File \"/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 259, in compute_gradients\n        grads = tape.gradient(loss, var_list)\n\n    LookupError: gradient registry has no entry for: ResizeArea\n\n"}